use std::net::{IpAddr,SocketAddr};use std::time::{Duration,Instant};use tokio::time::timeout;
pub const T:Duration=Duration::from_millis(2000);
#[allow(dead_code)]#[derive(Clone,Debug,Default)]pub struct Route{pub ip:Option<IpAddr>,pub iface:Option<String>,pub index:u32}
impl Route{pub fn direct()->Self{Self::default()}pub fn bound(ip:IpAddr,iface:String,index:u32)->Self{Self{ip:Some(ip),iface:Some(iface),index}}pub fn is_bound(&self)->bool{self.ip.is_some()}}
fn raw_socket(route:&Route,v4:bool)->std::io::Result<socket2::Socket>{use socket2::{Domain,Protocol,Socket,Type};let socket=Socket::new(if v4{Domain::IPV4}else{Domain::IPV6},Type::STREAM,Some(Protocol::TCP))?;socket.set_nonblocking(true)?;if let Some(ip)=route.ip{#[cfg(target_os="linux")]if let Some(name)=&route.iface{let _=socket.bind_device(Some(name.as_bytes()));}#[cfg(target_os="macos")]if route.index>0{let _=socket.bind_device_by_index_v4(std::num::NonZeroU32::new(route.index));}socket.bind(&SocketAddr::new(ip,0).into())?;}Ok(socket)}
async fn connect(route:&Route,addr:SocketAddr,refused_ok:bool)->Option<u32>{let started=Instant::now();let socket=raw_socket(route,addr.is_ipv4()).ok()?;let stream:std::net::TcpStream=socket.into();let socket=tokio::net::TcpSocket::from_std_stream(stream);match timeout(T,socket.connect(addr)).await{Ok(Ok(_))=>Some(started.elapsed().as_millis()as u32),Ok(Err(e))if refused_ok&&e.kind()==std::io::ErrorKind::ConnectionRefused=>Some(started.elapsed().as_millis()as u32),_=>None}}
pub async fn tcp(addr:SocketAddr)->Option<u32>{connect(&Route::direct(),addr,false).await}pub async fn tcp_via(route:&Route,addr:SocketAddr)->Option<u32>{connect(route,addr,false).await}pub async fn tcp_reach_via(route:&Route,addr:SocketAddr)->Option<u32>{connect(route,addr,true).await}
pub async fn icmp(ip:IpAddr)->Option<u32>{let client=surge_ping::Client::new(&surge_ping::Config::default()).ok()?;let mut pinger=client.pinger(ip,surge_ping::PingIdentifier(rand::random())).await;pinger.timeout(T);match pinger.ping(surge_ping::PingSequence(0),&[0u8;32]).await{Ok((_,d))=>Some(d.as_millis()as u32),Err(_)=>None}}
pub async fn ping_via(route:&Route,ip:IpAddr,fallback_port:u16)->Option<u32>{if !route.is_bound(){if let Some(ms)=icmp(ip).await{return Some(ms)}}tcp_reach_via(route,SocketAddr::new(ip,fallback_port)).await}pub async fn ping(ip:IpAddr,fallback_port:u16)->Option<u32>{ping_via(&Route::direct(),ip,fallback_port).await}
pub async fn http(client:&reqwest::Client,url:&str,dur:Duration)->Option<u32>{let started=Instant::now();match timeout(dur,client.get(url).send()).await{Ok(Ok(response))if response.status().is_success()=>Some(started.elapsed().as_millis()as u32),_=>None}}
pub fn client_via(route:&Route)->reqwest::Client{let mut builder=reqwest::Client::builder().no_proxy().timeout(Duration::from_secs(3)).user_agent("NetWatchIR/0.1");if let Some(ip)=route.ip{builder=builder.local_address(ip);}#[cfg(any(target_os="linux",target_os="macos"))]if let Some(name)=&route.iface{builder=builder.interface(name);}builder.build().expect("client")}pub fn direct_client()->reqwest::Client{client_via(&Route::direct())}
