use crate::{state::{NetState,Snapshot},AppState};use chrono::{Local,TimeZone,Timelike};use rusqlite::{params,Connection};use serde::Serialize;use std::{collections::HashMap,path::Path};
pub fn open(path:&Path)->anyhow::Result<Connection>{let c=Connection::open(path)?;c.execute_batch("PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,ts INTEGER NOT NULL,from_state TEXT,to_state TEXT,details TEXT); CREATE TABLE IF NOT EXISTS samples(ts INTEGER NOT NULL,state TEXT,domestic_ms INTEGER,intl_ms INTEGER,loss INTEGER); CREATE INDEX IF NOT EXISTS ev_ts ON events(ts); CREATE INDEX IF NOT EXISTS sm_ts ON samples(ts);")?;Ok(c)}
pub fn record_event(st:&AppState,from:NetState,to:NetState,s:&Snapshot){if let Some(c)=st.db.lock().as_ref(){let d=serde_json::json!({"gateway":s.gateway_ok,"domestic":s.domestic_ok,"international":s.international_ok,"dns":s.dns,"proxy":s.proxy,"tun":s.tun,"loss":s.loss_pct,"trigger":s.trigger});let _=c.execute("INSERT INTO events(ts,from_state,to_state,details) VALUES(?1,?2,?3,?4)",params![s.ts,from.name(),to.name(),d.to_string()]);}}
pub fn record_sample(st:&AppState,s:&Snapshot){if let Some(c)=st.db.lock().as_ref(){let _=c.execute("INSERT INTO samples(ts,state,domestic_ms,intl_ms,loss) VALUES(?1,?2,?3,?4,?5)",params![s.ts,s.state.name(),s.domestic_ping,s.international_ping,s.loss_pct]);}}
#[derive(Serialize)]pub struct EventRow{pub ts:i64,pub from:String,pub to:String,pub details:String}
pub fn events(st:&AppState,limit:u32)->Vec<EventRow>{let g=st.db.lock();let Some(c)=g.as_ref()else{return vec![]};let mut q=match c.prepare("SELECT ts,from_state,to_state,details FROM events ORDER BY ts DESC LIMIT ?1"){Ok(q)=>q,Err(_)=>return vec![]};q.query_map([limit],|r|Ok(EventRow{ts:r.get(0)?,from:r.get(1)?,to:r.get(2)?,details:r.get(3)?})).map(|it|it.filter_map(Result::ok).collect()).unwrap_or_default()}
#[derive(Serialize,Default)]pub struct Stats{pub since:i64,pub seconds_by_state:HashMap<String,i64>,pub changes:u32,pub outages:u32,pub national:u32,pub samples:Vec<(i64,Option<u32>,Option<u32>)>}
pub fn stats(st:&AppState,days:u32)->Stats{let now=chrono::Utc::now().timestamp();let since=now-days as i64*86400;let mut out=Stats{since,..Default::default()};let g=st.db.lock();let Some(c)=g.as_ref()else{return out};let mut rows:Vec<(i64,String)>=c.prepare("SELECT ts,to_state FROM events WHERE ts>=?1 ORDER BY ts ASC").and_then(|mut q|q.query_map([since],|r|Ok((r.get(0)?,r.get(1)?))).map(|it|it.filter_map(Result::ok).collect())).unwrap_or_default();rows.insert(0,(since,"ONLINE".into()));for(i,(ts,state))in rows.iter().enumerate(){let end=rows.get(i+1).map(|x|x.0).unwrap_or(now);*out.seconds_by_state.entry(state.clone()).or_insert(0)+=(end-ts).max(0);if i>0{out.changes+=1;match state.as_str(){"OFFLINE"|"NO_LINK"=>out.outages+=1,"NATIONAL"=>out.national+=1,_=>{}}}}out.samples=c.prepare("SELECT ts,domestic_ms,intl_ms FROM samples WHERE ts>=?1 ORDER BY ts ASC").and_then(|mut q|q.query_map([since],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).map(|it|it.filter_map(Result::ok).collect())).unwrap_or_default();out}
const MAX_GAP:i64=60;
#[derive(Serialize,Clone,Default)]pub struct Segment{pub start:i64,pub end:i64,pub state:String}
#[derive(Serialize,Default)]pub struct Bucket{pub ts:i64,pub dominant:String,pub free_pct:u8,pub intl_ms:Option<u32>,pub dom_ms:Option<u32>,pub loss:u8,pub known:bool}
#[derive(Serialize,Default,Clone)]pub struct Kpis{pub free_pct:f32,pub usable_pct:f32,pub unknown_min:u32,pub national_min:u32,pub outage_min:u32,pub degraded_min:u32,pub vpn_issue_min:u32,pub incidents:u32,pub longest_outage_min:u32,pub avg_intl_ms:Option<u32>,pub p95_intl_ms:Option<u32>,pub avg_dom_ms:Option<u32>,pub avg_loss:u8}
#[derive(Serialize,Default)]pub struct DayRow{pub ts:i64,pub kpis:Kpis}
#[derive(Serialize,Default)]pub struct Analytics{pub period:String,pub since:i64,pub until:i64,pub kpis:Kpis,pub prev:Kpis,pub segments:Vec<Segment>,pub segments_12h:Vec<Segment>,pub buckets:Vec<Bucket>,pub days:Vec<DayRow>,pub series:Vec<(i64,Option<u32>,Option<u32>,u8)>,pub worst_hours:Vec<(u8,u32)>}
struct Sm{ts:i64,state:String,dom:Option<u32>,intl:Option<u32>,loss:u8}
fn local_midnight(days_back:i64)->i64{let d=Local::now().date_naive()-chrono::Duration::days(days_back);Local.from_local_datetime(&d.and_hms_opt(0,0,0).unwrap()).single().map(|t|t.timestamp()).unwrap_or_else(||chrono::Utc::now().timestamp()-86400*days_back)}
fn hour_of(ts:i64)->u8{Local.timestamp_opt(ts,0).single().map(|d|d.hour() as u8).unwrap_or(0)}
fn is_outage(s:&str)->bool{matches!(s,"OFFLINE"|"NO_LINK"|"NATIONAL")}
fn load(c:&Connection,since:i64,until:i64)->Vec<Sm>{c.prepare("SELECT ts,state,domestic_ms,intl_ms,loss FROM samples WHERE ts>=?1 AND ts<?2").and_then(|mut q|q.query_map([since,until],|r|Ok(Sm{ts:r.get(0)?,state:r.get(1)?,dom:r.get(2)?,intl:r.get(3)?,loss:r.get::<_,Option<u8>>(4)?.unwrap_or(0)})).map(|it|it.filter_map(Result::ok).collect())).unwrap_or_default()}
fn build_segments(samples:&[Sm],until:i64)->Vec<Segment>{let mut out:Vec<Segment>=Vec::new();for(i,s)in samples.iter().enumerate(){let next=samples.get(i+1).map(|n|n.ts).unwrap_or(until).max(s.ts);let end=next.min(s.ts+MAX_GAP);match out.last_mut(){Some(last)if last.state==s.state&&last.end>=s.ts=>last.end=end,_=>out.push(Segment{start:s.ts,end,state:s.state.clone()})}if next>end{out.push(Segment{start:end,end:next,state:"UNKNOWN".into()});}}out}
fn clip(segs:&[Segment],a:i64,b:i64)->Vec<Segment>{segs.iter().filter(|s|s.end>a&&s.start<b).map(|s|Segment{start:s.start.max(a),end:s.end.min(b),state:s.state.clone()}).collect()}
fn average(values:&[u32])->Option<u32>{if values.is_empty(){None}else{Some((values.iter().map(|&v|v as u64).sum::<u64>()/values.len()as u64)as u32)}}
fn kpis(segs:&[Segment],samples:&[Sm])->Kpis{let mut by:HashMap<&str,i64>=HashMap::new();let mut known=0;for s in segs{let d=(s.end-s.start).max(0);if s.state!="UNKNOWN"{known+=d}*by.entry(s.state.as_str()).or_insert(0)+=d;}let g=|k:&str|*by.get(k).unwrap_or(&0);let pct=|v:i64|if known>0{(v as f32*100.0/known as f32).clamp(0.0,100.0)}else{0.0};let(mut incidents,mut longest,mut run,mut prev_out)=(0i64,0i64,0i64,false);for s in segs{let outage=is_outage(&s.state);if outage{if !prev_out{incidents+=1}run+=(s.end-s.start).max(0);longest=longest.max(run)}else{run=0}prev_out=outage}let mut intl:Vec<u32>=samples.iter().filter_map(|s|s.intl).collect();intl.sort_unstable();let dom:Vec<u32>=samples.iter().filter_map(|s|s.dom).collect();let loss=if samples.is_empty(){0}else{(samples.iter().map(|s|s.loss as u32).sum::<u32>()/samples.len()as u32)as u8};Kpis{free_pct:pct(g("ONLINE")),usable_pct:pct(g("ONLINE")+g("DEGRADED")+g("UNSTABLE")),unknown_min:(g("UNKNOWN")/60)as u32,national_min:(g("NATIONAL")/60)as u32,outage_min:((g("OFFLINE")+g("NO_LINK"))/60)as u32,degraded_min:((g("DEGRADED")+g("UNSTABLE"))/60)as u32,vpn_issue_min:((g("PROXY_STALE")+g("VPN_BROKEN")+g("DNS_ISSUE"))/60)as u32,incidents:incidents as u32,longest_outage_min:(longest/60)as u32,avg_intl_ms:average(&intl),p95_intl_ms:intl.get(intl.len().saturating_sub(1)*95/100).copied(),avg_dom_ms:average(&dom),avg_loss:loss}}
fn buckets(segs:&[Segment],samples:&[Sm],since:i64,n:usize)->Vec<Bucket>{(0..n).map(|i|{let a=since+i as i64*3600;let b=a+3600;let mut by:HashMap<String,i64>=HashMap::new();for s in clip(segs,a,b){*by.entry(s.state).or_insert(0)+=s.end-s.start;}let known=by.iter().filter(|(k,_)|k.as_str()!="UNKNOWN").map(|(_,v)|*v).sum::<i64>();let dominant=by.iter().filter(|(k,_)|k.as_str()!="UNKNOWN").max_by_key(|(_,v)|**v).map(|(k,_)|k.clone()).unwrap_or_else(||"UNKNOWN".into());let free=by.get("ONLINE").copied().unwrap_or(0);let sm:Vec<&Sm>=samples.iter().filter(|s|s.ts>=a&&s.ts<b).collect();let avg=|which:fn(&Sm)->Option<u32>|{let v:Vec<u32>=sm.iter().filter_map(|s|which(s)).collect();average(&v)};Bucket{ts:a,dominant,free_pct:if known>0{(free*100/known)as u8}else{0},intl_ms:avg(|s|s.intl),dom_ms:avg(|s|s.dom),loss:if sm.is_empty(){0}else{(sm.iter().map(|s|s.loss as u32).sum::<u32>()/sm.len()as u32)as u8},known:known>0}}).collect()}
fn series(samples:&[Sm],max_pts:usize)->Vec<(i64,Option<u32>,Option<u32>,u8)>{if samples.is_empty(){return vec![]}let step=(samples.len()+max_pts-1)/max_pts;samples.chunks(step.max(1)).map(|chunk|{let avg=|which:fn(&Sm)->Option<u32>|{let v:Vec<u32>=chunk.iter().filter_map(|s|which(s)).collect();average(&v)};(chunk[0].ts,avg(|s|s.dom),avg(|s|s.intl),(chunk.iter().map(|s|s.loss as u32).sum::<u32>()/chunk.len()as u32)as u8)}).collect()}
pub fn analytics(st:&AppState,period:&str)->Analytics{let now=chrono::Utc::now().timestamp();let week=period=="week";let since=if week{local_midnight(6)}else{local_midnight(0)};let span=now-since;let mut out=Analytics{period:period.into(),since,until:now,..Default::default()};let guard=st.db.lock();let Some(c)=guard.as_ref()else{return out};let samples=load(c,since,now);let segments=build_segments(&samples,now);out.kpis=kpis(&segments,&samples);let previous=load(c,since-span,since);out.prev=kpis(&build_segments(&previous,since),&previous);out.buckets=buckets(&segments,&samples,since,if week{168}else{24});out.series=series(&samples,if week{500}else{300});if week{out.days=(0..7).map(|d|{let a=local_midnight(6-d);let b=if d==6{now}else{local_midnight(5-d)};let day:Vec<Sm>=samples.iter().filter(|s|s.ts>=a&&s.ts<b).map(|s|Sm{ts:s.ts,state:s.state.clone(),dom:s.dom,intl:s.intl,loss:s.loss}).collect();DayRow{ts:a,kpis:kpis(&clip(&segments,a,b),&day)}}).collect();}let mut hour_map:HashMap<u8,u32>=HashMap::new();for bucket in out.buckets.iter().filter(|b|b.known){*hour_map.entry(hour_of(bucket.ts)).or_insert(0)+=(100-bucket.free_pct as u32)*60/100;}let mut worst:Vec<(u8,u32)>=hour_map.into_iter().filter(|(_,minutes)|*minutes>0).collect();worst.sort_by(|a,b|b.1.cmp(&a.1));worst.truncate(3);out.worst_hours=worst;let s12=now-12*3600;let samples_12=load(c,s12,now);out.segments_12h=build_segments(&samples_12,now);out.segments=segments;out}
