mod commands; mod config; mod engine; mod history; mod hover; mod icon; mod popup; mod probes; mod speed; mod state; mod tray; mod watch;
#[cfg(windows)] mod taskbar;
use parking_lot::{Mutex,RwLock};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool,AtomicU64};
use std::time::Instant;
use tauri::{Manager,WindowEvent};
use tauri_plugin_autostart::MacosLauncher;
pub struct AppState{pub snapshot:Mutex<state::Snapshot>,pub speed:Mutex<speed::Speed>,pub settings:RwLock<config::Settings>,pub settings_path:Mutex<PathBuf>,pub db:Mutex<Option<rusqlite::Connection>>,pub popup_hold:AtomicBool,pub popup_gen:AtomicU64,pub pending_popup:Mutex<Option<popup::PopupPayload>>,pub tray_rect:Mutex<Option<(f64,f64,f64,f64)>>,pub kick:tokio::sync::Notify,pub checking:AtomicBool,pub last_check:Mutex<Instant>}
impl AppState{fn new()->Self{Self{snapshot:Mutex::new(state::Snapshot::default()),speed:Mutex::new(speed::Speed::default()),settings:RwLock::new(config::Settings::default()),settings_path:Mutex::new(PathBuf::new()),db:Mutex::new(None),popup_hold:AtomicBool::new(false),popup_gen:AtomicU64::new(0),pending_popup:Mutex::new(None),tray_rect:Mutex::new(None),kick:tokio::sync::Notify::new(),checking:AtomicBool::new(false),last_check:Mutex::new(Instant::now())}}fn init(&self,app:&tauri::AppHandle)->anyhow::Result<()>{let dir=app.path().app_data_dir()?;std::fs::create_dir_all(&dir)?;let sp=dir.join("settings.json");*self.settings.write()=config::load(&sp);*self.settings_path.lock()=sp;*self.db.lock()=Some(history::open(&dir.join("history.db"))?);Ok(())}}
pub fn run(){let _=env_logger::try_init();tauri::Builder::default().plugin(tauri_plugin_single_instance::init(|app,_,_|popup::open_dashboard(app))).plugin(tauri_plugin_autostart::init(MacosLauncher::LaunchAgent,None)).plugin(tauri_plugin_notification::init()).manage(AppState::new()).invoke_handler(tauri::generate_handler![commands::get_snapshot,commands::run_now,commands::get_settings,commands::set_settings,commands::get_events,commands::get_stats,commands::get_analytics,commands::get_speed,commands::speed_test,commands::disable_proxy,commands::popup_hold,commands::popup_close,commands::popup_ready,commands::open_dashboard,commands::widget_menu,commands::widget_hover,commands::widget_alive,commands::widget_rebuild]).setup(|app|{#[cfg(target_os="macos")]app.set_activation_policy(tauri::ActivationPolicy::Accessory);app.state::<AppState>().init(app.handle())?;tray::build(app.handle())?;tray::ensure_speed_tray(app.handle())?;#[cfg(windows)]taskbar::spawn_placer(app.handle().clone());let h=app.handle().clone();tauri::async_runtime::spawn(engine::run_loop(h.clone()));tauri::async_runtime::spawn(speed::run(h));Ok(())}).on_window_event(|w,e|{if let WindowEvent::CloseRequested{api,..}=e{if w.label()=="main"{api.prevent_close();let _=w.hide();}}}).build(tauri::generate_context!()).expect("failed to build app").run(|_,event|{if let tauri::RunEvent::ExitRequested{api,code,..}=event{if code.is_none(){api.prevent_exit();}}})}
