use crate::{tray, AppState};
use futures::StreamExt;
use serde::Serialize;
use std::{collections::{HashMap, VecDeque}, time::{Duration, Instant}};
use sysinfo::Networks;
use tauri::{AppHandle, Emitter, Manager};

#[derive(Debug, Clone, Serialize, Default)]
pub struct Speed { pub rx_bps:u64, pub tx_bps:u64, pub rx_peak:u64, pub tx_peak:u64, pub rx_total:u64, pub tx_total:u64, pub iface:String, pub history:VecDeque<(u64,u64)> }
const TUN_HINTS:&[&str]= &["wintun","wireguard","openvpn","hiddify","nekoray","nekobox","sing-tun","singbox","clash","v2ray","tun2socks","outline","psiphon"];
fn is_virtual(name:&str)->bool{let name=name.to_lowercase();name.starts_with("lo")||name.contains("loopback")||name.starts_with("tun")||name.starts_with("utun")||name.starts_with("wg")||name.starts_with("tap")||name.starts_with("docker")||name.starts_with("br-")||name.starts_with("veth")||name.starts_with("vmnet")||name.starts_with("vbox")||name.contains("vethernet")||name.contains("wsl")||name.contains("hyper-v")||name.contains("virtual")||name.contains("bluetooth")||TUN_HINTS.iter().any(|hint|name.contains(hint))}
pub fn fmt(bps:u64,_bytes:bool)->String{let kb=bps as f64/1024.0;if kb<1000.0{return format!("{kb:.0} KB/s");}let mb=kb/1024.0;if mb<10.0{format!("{mb:.1} MB/s")}else{format!("{mb:.0} MB/s")}}

pub async fn run(app:AppHandle){let mut networks=Networks::new_with_refreshed_list();let mut previous:HashMap<String,(u64,u64)>=HashMap::new();let mut accumulated=(0u64,0u64);let mut window:VecDeque<(Instant,u64,u64)>=VecDeque::new();let(mut ema_rx,mut ema_tx)=(0f64,0f64);let mut tick=0u32;loop{tokio::time::sleep(Duration::from_millis(500)).await;tick+=1;if tick%60==0{networks.refresh_list();}else{networks.refresh();}let now=Instant::now();let(mut physical_rx,mut physical_tx,mut all_rx,mut all_tx)=(0u64,0u64,0u64,0u64);let(mut top,mut iface)=(0u64,String::new());for(name,data)in networks.iter(){let current=(data.total_received(),data.total_transmitted());let(received,transmitted)=match previous.insert(name.clone(),current){Some(previous)if current.0>=previous.0&&current.1>=previous.1=>(current.0-previous.0,current.1-previous.1),_=>(0,0)};all_rx+=received;all_tx+=transmitted;if !is_virtual(name){physical_rx+=received;physical_tx+=transmitted;if received+transmitted>top{top=received+transmitted;iface=name.clone();}}}let(rx_delta,tx_delta)=if physical_rx+physical_tx==0&&all_rx+all_tx>0{(all_rx,all_tx)}else{(physical_rx,physical_tx)};accumulated.0+=rx_delta;accumulated.1+=tx_delta;window.push_back((now,accumulated.0,accumulated.1));while window.len()>2&&now.duration_since(window.front().unwrap().0)>Duration::from_millis(2500){window.pop_front();}let(t0,rx0,tx0)=*window.front().unwrap();let span=now.duration_since(t0).as_secs_f64();if span>=0.9{let(rx,tx)=((accumulated.0-rx0)as f64/span,(accumulated.1-tx0)as f64/span);ema_rx=if ema_rx==0.0{rx}else{ema_rx*0.4+rx*0.6};ema_tx=if ema_tx==0.0{tx}else{ema_tx*0.4+tx*0.6};if rx<1024.0{ema_rx=rx;}if tx<1024.0{ema_tx=tx;}}let(rx_bps,tx_bps)=(ema_rx as u64,ema_tx as u64);let state=app.state::<AppState>();let snapshot={let mut speed=state.speed.lock();speed.rx_bps=rx_bps;speed.tx_bps=tx_bps;speed.rx_peak=speed.rx_peak.max(rx_bps);speed.tx_peak=speed.tx_peak.max(tx_bps);speed.rx_total+=rx_delta;speed.tx_total+=tx_delta;if !iface.is_empty(){speed.iface=iface;}if tick%2==0{speed.history.push_back((rx_bps,tx_bps));if speed.history.len()>60{speed.history.pop_front();}}speed.clone()};if tick%2==0{let _=app.emit("speed",&snapshot);let tooltip_snapshot = { state.snapshot.lock().clone() }; tray::update_tooltip(&app, &tooltip_snapshot);}tray::on_speed(&app,rx_bps,tx_bps);}}

#[derive(Debug,Clone,Serialize,Default)]pub struct SpeedTest{pub down_bps:u64,pub up_bps:u64,pub latency_ms:Option<u32>,pub server:String}
#[derive(Serialize,Clone)]struct Progress{phase:&'static str,bps:u64,pct:u8}
pub async fn test(app:AppHandle,down_url:&str,up_url:&str)->anyhow::Result<SpeedTest>{let client=reqwest::Client::builder().timeout(Duration::from_secs(25)).user_agent("NetWatchIR/0.1").build()?;let mut result=SpeedTest{server:down_url.split('/').nth(2).unwrap_or("").into(),..Default::default()};let started=Instant::now();if client.head(down_url).send().await.is_ok(){result.latency_ms=Some(started.elapsed().as_millis()as u32);}let started=Instant::now();let mut received=0u64;let mut stream=client.get(down_url).send().await?.bytes_stream();while let Some(chunk)=stream.next().await{received+=chunk?.len()as u64;let elapsed=started.elapsed().as_secs_f64();let _=app.emit("speed-test",Progress{phase:"down",bps:(received as f64/elapsed.max(0.05))as u64,pct:(elapsed/8.0*100.0).min(100.0)as u8});if elapsed>8.0{break;}}result.down_bps=(received as f64/started.elapsed().as_secs_f64().max(0.05))as u64;let body=vec![0xA5u8;8*1024*1024];let started=Instant::now();let _=app.emit("speed-test",Progress{phase:"up",bps:0,pct:0});if client.post(up_url).body(body.clone()).send().await.is_ok(){result.up_bps=(body.len()as f64/started.elapsed().as_secs_f64().max(0.05))as u64;}let _=app.emit("speed-test",Progress{phase:"done",bps:result.down_bps,pct:100});Ok(result)}
