use crate::{tray, AppState};
use futures::StreamExt;
use serde::Serialize;
use std::{collections::VecDeque, time::{Duration, Instant}};
use sysinfo::Networks;
use tauri::{AppHandle, Emitter, Manager};

#[derive(Debug, Clone, Serialize, Default)]
pub struct Speed { pub rx_bps:u64, pub tx_bps:u64, pub rx_peak:u64, pub tx_peak:u64, pub rx_total:u64, pub tx_total:u64, pub iface:String, pub history:VecDeque<(u64,u64)> }
const TUN_HINTS:&[&str]= &["wintun","wireguard","openvpn","hiddify","nekoray","nekobox","sing-tun","singbox","clash","v2ray","tun2socks","outline","psiphon"];
fn skip(name:&str)->bool{let name=name.to_lowercase();name.starts_with("lo")||name.contains("loopback")||name.starts_with("tun")||name.starts_with("utun")||name.starts_with("wg")||name.starts_with("tap")||name.starts_with("docker")||name.starts_with("br-")||name.starts_with("veth")||name.starts_with("vmnet")||name.starts_with("vbox")||name.contains("vethernet")||name.contains("wsl")||name.contains("hyper-v")||name.contains("virtual")||TUN_HINTS.iter().any(|hint|name.contains(hint))}
pub fn fmt(bps:u64,bytes:bool)->String{let(mut value,mut index)=(if bytes{bps as f64}else{bps as f64*8.0},0);let units=if bytes{["B/s","KB/s","MB/s","GB/s"]}else{["b/s","Kb/s","Mb/s","Gb/s"]};while value>=1000.0&&index<3{value/=1000.0;index+=1;}if index==0{format!("{} {}",value as u64,units[index])}else if value>=100.0{format!("{value:.0} {}",units[index])}else{format!("{value:.1} {}",units[index])}}
pub async fn run(app:AppHandle){let mut networks=Networks::new_with_refreshed_list();let mut previous=std::collections::HashMap::<String,(u64,u64)>::new();let mut last=Instant::now();let mut tick=0u32;loop{tokio::time::sleep(Duration::from_secs(1)).await;tick+=1;if tick%30==0{networks.refresh_list();}else{networks.refresh();}let elapsed=last.elapsed().as_secs_f64().max(0.2);last=Instant::now();let(mut rx_bps,mut tx_bps,mut rx_total,mut tx_total)=(0,0,0,0);let(mut top_bytes,mut iface)=(0,String::new());let mut current=std::collections::HashMap::new();for(name,data)in networks.iter(){if skip(name){continue;}let(received,transmitted)=(data.received(),data.transmitted());let(old_received,old_transmitted)=previous.get(name).copied().unwrap_or((received,transmitted));let(rx,tx)=(received.saturating_sub(old_received),transmitted.saturating_sub(old_transmitted));current.insert(name.clone(),(received,transmitted));rx_total+=rx;tx_total+=tx;if rx+tx>top_bytes{top_bytes=rx+tx;iface=name.clone();}rx_bps+=(rx as f64/elapsed)as u64;tx_bps+=(tx as f64/elapsed)as u64;}previous=current;let state=app.state::<AppState>();let snapshot={let mut speed=state.speed.lock();speed.rx_bps=rx_bps;speed.tx_bps=tx_bps;speed.rx_peak=speed.rx_peak.max(rx_bps);speed.tx_peak=speed.tx_peak.max(tx_bps);speed.rx_total+=rx_total;speed.tx_total+=tx_total;if !iface.is_empty(){speed.iface=iface;}speed.history.push_back((rx_bps,tx_bps));if speed.history.len()>60{speed.history.pop_front();}speed.clone()};let _=app.emit("speed",&snapshot);if tick%2==0{tray::update_tooltip(&app,&state.snapshot.lock());}}}
#[derive(Debug,Clone,Serialize,Default)]pub struct SpeedTest{pub down_bps:u64,pub up_bps:u64,pub latency_ms:Option<u32>,pub server:String}
#[derive(Serialize,Clone)]struct Progress{phase:&'static str,bps:u64,pct:u8}
pub async fn test(app:AppHandle,down_url:&str,up_url:&str)->anyhow::Result<SpeedTest>{let client=reqwest::Client::builder().timeout(Duration::from_secs(25)).user_agent("NetWatchIR/0.1").build()?;let mut result=SpeedTest{server:down_url.split('/').nth(2).unwrap_or("").into(),..Default::default()};let started=Instant::now();if client.head(down_url).send().await.is_ok(){result.latency_ms=Some(started.elapsed().as_millis()as u32);}let started=Instant::now();let mut received=0u64;let mut stream=client.get(down_url).send().await?.bytes_stream();while let Some(chunk)=stream.next().await{received+=chunk?.len()as u64;let elapsed=started.elapsed().as_secs_f64();let _=app.emit("speed-test",Progress{phase:"down",bps:(received as f64/elapsed.max(0.05))as u64,pct:(elapsed/8.0*100.0).min(100.0)as u8});if elapsed>8.0{break;}}result.down_bps=(received as f64/started.elapsed().as_secs_f64().max(0.05))as u64;let body=vec![0xA5u8;8*1024*1024];let started=Instant::now();let _=app.emit("speed-test",Progress{phase:"up",bps:0,pct:0});if client.post(up_url).body(body.clone()).send().await.is_ok(){result.up_bps=(body.len()as f64/started.elapsed().as_secs_f64().max(0.05))as u64;}let _=app.emit("speed-test",Progress{phase:"done",bps:result.down_bps,pct:100});Ok(result)}