use crate::{config,icon,popup,probes::proxy,state::{NetState,Snapshot},AppState};use parking_lot::Mutex;use std::{sync::atomic::Ordering::SeqCst,time::Duration};use tauri::async_runtime::JoinHandle;use tauri::menu::{CheckMenuItem,Menu,MenuItem,PredefinedMenuItem};use tauri::tray::{MouseButton,MouseButtonState,TrayIconBuilder,TrayIconEvent};use tauri::{AppHandle,Manager};
pub const TRAY_ID:&str="main-tray";
pub fn build(app:&AppHandle)->tauri::Result<()>{let open=MenuItem::with_id(app,"open","داشبورد و آمار",true,None::<&str>)?;let check=MenuItem::with_id(app,"check","بررسی مجدد",true,None::<&str>)?;let prx=MenuItem::with_id(app,"proxy","خاموش‌کردن پروکسی سیستم",true,None::<&str>)?;let quiet=CheckMenuItem::with_id(app,"quiet","حالت سکوت",true,false,None::<&str>)?;let quit=MenuItem::with_id(app,"quit","خروج",true,None::<&str>)?;let sep=PredefinedMenuItem::separator(app)?;let menu=Menu::with_items(app,&[&open,&check,&prx,&quiet,&sep,&quit])?;TrayIconBuilder::with_id(TRAY_ID).icon(icon::make([120,120,120,255],icon::Shape::Solid,None)).tooltip("NetWatch").menu(&menu).show_menu_on_left_click(false).on_menu_event(|app,e|match e.id().as_ref(){"open"=>popup::open_dashboard(app),"check"=>app.state::<AppState>().kick.notify_one(),"proxy"=>{let _=proxy::disable();app.state::<AppState>().kick.notify_one()},"quiet"=>{let st=app.state::<AppState>();let mut settings=st.settings.write();settings.quiet=!settings.quiet;let _=config::save(&st.settings_path.lock(),&settings);},"quit"=>app.exit(0),_=>{}}).on_tray_icon_event(|tray,e|{let app=tray.app_handle();let rect=match &e{TrayIconEvent::Click{rect,..}|TrayIconEvent::DoubleClick{rect,..}|TrayIconEvent::Enter{rect,..}|TrayIconEvent::Move{rect,..}|TrayIconEvent::Leave{rect,..}=>Some(rect),_=>None};if let Some(rect)=rect{let scale=app.primary_monitor().ok().flatten().map(|m|m.scale_factor()).unwrap_or(1.0);let p=rect.position.to_logical::<f64>(scale);let size=rect.size.to_logical::<f64>(scale);if size.width>0.0{*app.state::<AppState>().tray_rect.lock()=Some((p.x,p.y,size.width,size.height));}}if let TrayIconEvent::Click{button:MouseButton::Left,button_state:MouseButtonState::Up,..}=e{popup::open_dashboard(&app)}}).build(app)?;Ok(())}
static LAST_ICON: Mutex<Option<NetState>> = Mutex::new(None);
fn shape(state:NetState)->icon::Shape{if state==NetState::Unstable{icon::Shape::Ring}else{icon::Shape::Solid}}
pub fn set_state_icon(app:&AppHandle,state:NetState){let mut last=LAST_ICON.lock();if *last==Some(state){return;}if let Some(tray)=app.tray_by_id(TRAY_ID){if tray.set_icon(Some(icon::make(state.color(),shape(state),None))).is_ok(){*last=Some(state);}}}
pub fn spin(app:&AppHandle)->Option<JoinHandle<()>>{if cfg!(target_os="linux"){return None;}let app=app.clone();Some(tauri::async_runtime::spawn(async move{let state=app.state::<AppState>();let mut index=0u32;tokio::time::sleep(Duration::from_millis(400)).await;while state.checking.load(SeqCst){let current=state.snapshot.lock().state;if let Some(tray)=app.tray_by_id(TRAY_ID){let _=tray.set_icon(Some(icon::make(current.color(),shape(current),Some(index as f32*0.785))));*LAST_ICON.lock()=None;}index=(index+1)%8;tokio::time::sleep(Duration::from_millis(120)).await;}}))}
pub fn update_tooltip(app:&AppHandle,s:&Snapshot){let Some(tray)=app.tray_by_id(TRAY_ID)else{return};let format_ms=|value:Option<u32>|value.map(|ms|format!("{ms}ms")).unwrap_or_else(||"—".into());let mut tip=format!("{} {}\nداخلی: {} | خارجی: {}",s.state.emoji(),s.state.title(),format_ms(s.domestic_ping),format_ms(s.international_ping));if let Some(ms)=s.vpn_ping{tip.push_str(&format!(" | تونل: {ms}ms"));}if s.loss_pct>0{tip.push_str(&format!(" | پکت‌لاس: {}%",s.loss_pct));}if s.via_vpn{tip.push_str(&format!("\n🛡️ VPN فعال — خروجی: {}",s.exit.country.clone().unwrap_or_default()));}else if let Some(tun)=&s.tun{tip.push_str(&format!("\nTUN بالا ولی خروجی ایران است: {tun}"));}else if s.proxy.configured{tip.push_str(&format!("\nپروکسی {}:{} {}",s.proxy.host,s.proxy.port,if s.proxy.listening{"روشن ولی کار نمی‌کند ✗"}else{"بسته ✗"}));}if let Some(note)=&s.note{tip.push_str(&format!("\n{note}"));}let _=tray.set_tooltip(Some(tip));}
pub fn update(app:&AppHandle,s:&Snapshot){set_state_icon(app,s.state);update_tooltip(app,s);}
