(() => {
  const { invoke } = window.__TAURI__.core;
  const { listen } = window.__TAURI__.event;
  const $ = (id) => document.getElementById(id);
  const fa = (value) => Number(value).toLocaleString("fa-IR");
  const split = (bps) => { let value = bps / (1024 * 1024), index = 0; while (value >= 1000 && index < 2) { value /= 1000; index++; } const units = ["MB/s", "GB/s", "TB/s"]; return [value >= 10 ? value.toFixed(0) : value.toFixed(1), units[index]]; };
  const format = (bps) => split(bps).join(" ");
  const total = (value) => { let index = 0; while (value >= 1024 && index < 4) { value /= 1024; index++; } return `${value.toFixed(index ? 1 : 0)} ${["B", "KB", "MB", "GB", "TB"][index]}`; };
  function draw(history) { const canvas = $("sp-chart"), dpr = devicePixelRatio || 1, width = canvas.clientWidth || 300, height = 70; canvas.width = width * dpr; canvas.height = height * dpr; const ctx = canvas.getContext("2d"); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, width, height); const middle = height / 2, max = Math.max(50000, ...history.map(([rx, tx]) => Math.max(rx, tx))); const x = (index) => width - ((59 - index) / 59) * width; ctx.strokeStyle = "rgba(255,255,255,.1)"; ctx.beginPath(); ctx.moveTo(0, middle + .5); ctx.lineTo(width, middle + .5); ctx.stroke(); const area = (field, color, direction) => { const gradient = ctx.createLinearGradient(0, direction > 0 ? middle : 0, 0, direction > 0 ? height : middle); gradient.addColorStop(direction > 0 ? 0 : 1, color + "88"); gradient.addColorStop(direction > 0 ? 1 : 0, color + "05"); ctx.beginPath(); ctx.moveTo(x(60 - history.length), middle); history.forEach((sample, index) => ctx.lineTo(x(60 - history.length + index), middle - direction * (sample[field] / max) * (middle - 4))); ctx.lineTo(x(59), middle); ctx.closePath(); ctx.fillStyle = gradient; ctx.fill(); ctx.beginPath(); history.forEach((sample, index) => { const px = x(60 - history.length + index), py = middle - direction * (sample[field] / max) * (middle - 4); index ? ctx.lineTo(px, py) : ctx.moveTo(px, py); }); ctx.strokeStyle = color; ctx.lineWidth = 1.5; ctx.stroke(); }; area(0, "#22c55e", 1); area(1, "#3b82f6", -1); ctx.fillStyle = "#52525b"; ctx.font = "9px sans-serif"; ctx.fillText(`↓ ${format(max)}`, 4, 10); ctx.fillText(`↑ ${format(max)}`, 4, height - 3); }
  function render(speed) { const [rxValue, rxUnit] = split(speed.rx_bps), [txValue, txUnit] = split(speed.tx_bps); $("sp-rx").textContent = fa(rxValue); $("sp-rxu").textContent = rxUnit; $("sp-rxp").textContent = `اوج: ${format(speed.rx_peak)}`; $("sp-tx").textContent = fa(txValue); $("sp-txu").textContent = txUnit; $("sp-txp").textContent = `اوج: ${format(speed.tx_peak)}`; $("sp-iface").textContent = speed.iface ? `(${speed.iface})` : ""; $("sp-total").textContent = `مصرف از شروع برنامه: ↓ ${total(speed.rx_total)} · ↑ ${total(speed.tx_total)}`; draw([...speed.history]); }
  $("sp-unit").hidden = true;
  $("sp-test-btn").onclick = async () => { const button = $("sp-test-btn"), result = $("sp-test-res"); button.disabled = true; result.textContent = "در حال اتصال…"; try { const test = await invoke("speed_test"); result.innerHTML = `<b style="color:#22c55e">↓ ${format(test.down_bps)}</b> · <b style="color:#3b82f6">↑ ${format(test.up_bps)}</b>${test.latency_ms != null ? ` · ${fa(test.latency_ms)}ms` : ""} <small style="color:#71717a">(${test.server})</small>`; } catch { result.textContent = "تست ناموفق — احتمالاً بین‌الملل قطع است"; } button.disabled = false; };
  listen("speed-test", ({ payload }) => { if (payload.phase !== "done") $("sp-test-res").textContent = `${payload.phase === "down" ? "دانلود" : "آپلود"} ${format(payload.bps)} … ${fa(payload.pct)}%`; });
  invoke("get_speed").then(render); listen("speed", (event) => render(event.payload));
})();